### ISSUE TITLE
Usage of other Python libraries 

### ISSUE THREAD

**Issue by jcoop1219** [jcoop1219/bme547ci#10]
Are we allowed to use other Python libraries to get functions which help with the fuzzy string matching?

**Comment by dward2** [comment]
Yes.  You can use an existing published package that you can import.  Do not find other code and cut and paste it into your own code.  But, importing a published package and using its functionality is acceptable.  Make sure to create a requirements.txt or environment.yml file that makes the needed virtual environment with the package installed, and push that file to GitHub, so that I know what files to install when I test your code.

**Comment by jcoop1219** [comment]
Got it, thanks! And yes, was planning to install the library with pip and import a specific function for usage in my code (no cut-and-paste). I'll include the `requirements.txt` file in Github (it's needed for Travis CI to work anyway) and also post the contents of it in the README.
